import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { Container } from "@/components/Container";
import { Section } from "@/components/Section";
import { CTA } from "@/components/CTA";
import { Badge } from "@/components/Badge";
import { products } from "@/content/products";
import { site } from "@/content/site";

type Props = {
  params: Promise<{ slug: string }>;
};

export function generateStaticParams(): Array<{ slug: string }> {
  return products.map((p) => ({ slug: p.slug }));
}

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { slug } = await params;
  const product = products.find((p) => p.slug === slug);

  if (!product) {
    return { title: "Product | Sovereign Compliance Systems" };
  }

  return {
    title: `${product.name} | Sovereign Compliance Systems`,
    description: product.oneLiner,
  };
}

function FlagshipStory() {
  return (
    <>
      <div className="glass borderGlow rounded-2xl p-8">
        <div className="text-sm font-semibold text-gold">
          {site.taglineTop}. {site.taglineBottom}.
        </div>

        <h1 className="mt-3 text-3xl font-semibold tracking-tight">
          Sovereign Vault AI Platform
        </h1>

        <p className="mt-3 max-w-3xl text-sm text-muted">
          A flagship transaction platform for high value reservations, deposits,
          approvals, fraud resistance, and evidence grade audit trails. Built
          for premium brands that need speed, proof, and control.
        </p>

        <div className="mt-5 flex flex-wrap items-center gap-2">
          <Badge>Flagship</Badge>
          <Badge>Projects from 100,000 AED+</Badge>
          <Badge>Luxury Automotive Primary</Badge>
        </div>

        <div className="mt-6 grid gap-3 md:grid-cols-3">
          <div className="rounded-2xl border border-line bg-bg p-5">
            <div className="text-sm font-semibold">Less work</div>
            <div className="mt-2 text-sm text-muted">
              AI triage, automated routing, guided workflows, and evidence packs
              generated by the system.
            </div>
          </div>
          <div className="rounded-2xl border border-line bg-bg p-5">
            <div className="text-sm font-semibold">More flow</div>
            <div className="mt-2 text-sm text-muted">
              Reservations, deposits, and approvals move forward with tight
              controls and minimal friction.
            </div>
          </div>
          <div className="rounded-2xl border border-line bg-bg p-5">
            <div className="text-sm font-semibold">More proof</div>
            <div className="mt-2 text-sm text-muted">
              Every action is time stamped. Every decision has a trail. Every
              dispute has an evidence pack.
            </div>
          </div>
        </div>
      </div>

      <Section
        title="A luxury sales story that converts"
        subtitle="Your customer sees clarity and confidence. Your team sees control and traceability."
      >
        <div className="grid gap-4 md:grid-cols-2">
          <div className="glass borderGlow rounded-2xl p-6">
            <div className="text-sm font-semibold">Customer experience</div>
            <ul className="mt-3 list-disc space-y-1 pl-5 text-sm text-muted">
              <li>Reserve a specific asset with clear hold rules</li>
              <li>
                Pay a deposit with transparent disclosures and confirmations
              </li>
              <li>Track status in a secure portal</li>
              <li>
                Request more media, inspections, or appointments without chaos
              </li>
              <li>Receive receipts and acceptance proof automatically</li>
            </ul>
          </div>

          <div className="glass borderGlow rounded-2xl p-6">
            <div className="text-sm font-semibold">Internal operations</div>
            <ul className="mt-3 list-disc space-y-1 pl-5 text-sm text-muted">
              <li>Approvals, overrides, and exceptions are controlled</li>
              <li>
                Fraud signals route into a review queue with AI assisted triage
              </li>
              <li>Every staff action is logged and time stamped</li>
              <li>Evidence packs export in seconds</li>
              <li>Automation reduces repetitive admin work</li>
            </ul>
          </div>
        </div>
      </Section>

      <Section
        title="Platform preview"
        subtitle="A real world preview of how the platform reduces staff steps, captures proof, and exports evidence on demand."
      >
        <div className="grid gap-6 md:grid-cols-2">
          {/* 1 */}
          <div className="glass borderGlow rounded-2xl p-6">
            <div className="kicker mb-2 text-xs font-semibold tracking-widest text-gold">
              RESERVATION AND DEPOSIT FLOW
            </div>
            <div className="mb-2 text-lg font-semibold text-white">
              One deal timeline, no chasing
            </div>
            <div className="mb-4 text-sm text-muted">
              Deposits, terms acceptance, and status changes are recorded
              automatically with timestamps.
            </div>

            <div className="rounded-2xl border border-white/10 bg-black/20 p-4">
              <div className="mb-3 flex items-center justify-between text-xs text-muted">
                <span>Deal ID</span>
                <span className="text-text font-semibold">SV-10482</span>
              </div>

              <ul className="space-y-3">
                {[
                  ["Reservation link sent", "Tracked link delivery"],
                  ["Terms accepted", "Consent and disclosure captured"],
                  ["Deposit received", "Receipt and reference saved"],
                  ["Hold expires", "Auto release unless extended"],
                ].map(([a, b], i) => (
                  <li key={i} className="flex gap-3">
                    <span className="mt-1 h-2 w-2 rounded-full bg-gold" />
                    <div>
                      <div className="text-sm font-semibold text-white">
                        {a}
                      </div>
                      <div className="text-xs text-muted">{b}</div>
                    </div>
                  </li>
                ))}
              </ul>
            </div>
          </div>

          {/* 2 */}
          <div className="glass borderGlow rounded-2xl p-6">
            <div className="kicker mb-2 text-xs font-semibold tracking-widest text-gold">
              APPROVALS CONSOLE
            </div>
            <div className="mb-2 text-lg font-semibold text-white">
              Approvals with reason notes and change logs
            </div>
            <div className="mb-4 text-sm text-muted">
              Staff request. Managers approve. The system records what changed,
              who approved, and why.
            </div>

            <div className="rounded-2xl border border-white/10 bg-black/20 p-4">
              <div className="mb-3 grid grid-cols-4 gap-2 text-[11px] text-muted">
                <div>Request</div>
                <div>Status</div>
                <div>Owner</div>
                <div>Proof</div>
              </div>

              <div className="space-y-2">
                {[
                  ["Discount", "Pending", "Manager", "Log"],
                  ["Refund", "Approved", "Manager", "Receipt"],
                  ["Override", "Denied", "Lead", "Note"],
                ].map(([a, b, c, d], i) => (
                  <div
                    key={i}
                    className="grid grid-cols-4 gap-2 rounded-xl border border-white/10 bg-black/30 p-3 text-xs"
                  >
                    <div className="text-white">{a}</div>
                    <div className="text-muted">{b}</div>
                    <div className="text-muted">{c}</div>
                    <div className="text-gold">{d}</div>
                  </div>
                ))}
              </div>
            </div>
          </div>

          {/* 3 */}
          <div className="glass borderGlow rounded-2xl p-6">
            <div className="kicker mb-2 text-xs font-semibold tracking-widest text-gold">
              CASE MANAGEMENT QUEUE
            </div>
            <div className="mb-2 text-lg font-semibold text-white">
              Flagged events and exceptions in one inbox
            </div>
            <div className="mb-4 text-sm text-muted">
              Every exception becomes a tracked case with notes and linked
              evidence.
            </div>

            <div className="rounded-2xl border border-white/10 bg-black/20 p-4">
              <div className="mb-2 flex items-center justify-between text-xs text-muted">
                <span>Queue</span>
                <span>Live</span>
              </div>

              <div className="space-y-3">
                {[
                  ["Refund request", "Needs manager approval", "High"],
                  ["Deposit mismatch", "Payer name mismatch", "High"],
                  ["Discount override", "Reason note missing", "Medium"],
                  ["Hold extension", "Rule exception", "Low"],
                ].map(([a, b, c], i) => (
                  <div
                    key={i}
                    className="flex items-start justify-between gap-4"
                  >
                    <div>
                      <div className="text-sm font-semibold text-white">
                        {a}
                      </div>
                      <div className="text-xs text-muted">{b}</div>
                    </div>
                    <span className="rounded-full border border-white/10 bg-black/30 px-2 py-1 text-[11px] text-muted">
                      {c}
                    </span>
                  </div>
                ))}
              </div>
            </div>
          </div>

          {/* 4 */}
          <div className="glass borderGlow rounded-2xl p-6">
            <div className="kicker mb-2 text-xs font-semibold tracking-widest text-gold">
              FRAUD CONTROLS AND MONITORING
            </div>
            <div className="mb-2 text-lg font-semibold text-white">
              Less manual review, more controlled decisions
            </div>
            <div className="mb-4 text-sm text-muted">
              Velocity limits, risk scoring, and identity checks reduce fraud
              while protecting conversion.
            </div>

            <div className="rounded-2xl border border-white/10 bg-black/20 p-4">
              <div className="mb-2 text-xs text-muted">Active rules</div>

              <div className="space-y-2">
                {[
                  ["Velocity limit", "5 attempts per 10 minutes", "On"],
                  ["Step up verification", "Risk score 70+", "On"],
                  ["Device repeat", "Known device flagged", "On"],
                ].map(([a, b, c], i) => (
                  <div
                    key={i}
                    className="flex items-center justify-between rounded-xl border border-white/10 bg-black/30 p-3"
                  >
                    <div>
                      <div className="text-sm font-semibold text-white">
                        {a}
                      </div>
                      <div className="text-xs text-muted">{b}</div>
                    </div>
                    <span className="rounded-full border border-white/10 bg-black/40 px-2 py-1 text-[11px] text-muted">
                      {c}
                    </span>
                  </div>
                ))}
              </div>
            </div>
          </div>

          {/* 5 */}
          <div className="glass borderGlow rounded-2xl p-6">
            <div className="kicker mb-2 text-xs font-semibold tracking-widest text-gold">
              EVIDENCE VAULT EXPORT
            </div>
            <div className="mb-2 text-lg font-semibold text-white">
              One click proof pack export
            </div>
            <div className="mb-4 text-sm text-muted">
              Exports include the deal timeline, receipts, acceptances,
              approvals, and attached evidence.
            </div>

            <div className="rounded-2xl border border-white/10 bg-black/20 p-4">
              <div className="mb-2 flex items-center justify-between text-xs text-muted">
                <span>Export pack</span>
                <span>ZIP + PDF</span>
              </div>

              <div className="space-y-2">
                {[
                  ["timeline.pdf", "Deal summary and events"],
                  ["receipts.pdf", "Deposit receipts"],
                  ["acceptance.json", "Terms acceptance record"],
                  ["attachments/", "Photos and documents"],
                ].map(([a, b], i) => (
                  <div
                    key={i}
                    className="flex items-center justify-between rounded-xl border border-white/10 bg-black/30 p-3"
                  >
                    <div className="text-sm font-semibold text-white">{a}</div>
                    <div className="text-xs text-muted">{b}</div>
                  </div>
                ))}
              </div>

              <div className="mt-3 rounded-xl border border-white/10 bg-black/30 p-3 text-xs text-muted">
                Manifest and hashes included for integrity.
              </div>
            </div>
          </div>

          {/* 6 */}
          <div className="glass borderGlow rounded-2xl p-6">
            <div className="kicker mb-2 text-xs font-semibold tracking-widest text-gold">
              AUTOMATION AND INTEGRATIONS
            </div>
            <div className="mb-2 text-lg font-semibold text-white">
              Notifications, routing, and system hooks
            </div>
            <div className="mb-4 text-sm text-muted">
              Webhooks and automations reduce staff follow ups and keep every
              step tracked.
            </div>

            <div className="rounded-2xl border border-white/10 bg-black/20 p-4">
              <div className="space-y-2">
                {[
                  ["Deposit received", "Notify sales and finance"],
                  ["Approval required", "Create manager task"],
                  ["Hold expiring", "Auto remind or auto release"],
                  ["Export requested", "Generate proof pack"],
                ].map(([a, b], i) => (
                  <div
                    key={i}
                    className="rounded-xl border border-white/10 bg-black/30 p-3"
                  >
                    <div className="text-sm font-semibold text-white">{a}</div>
                    <div className="text-xs text-muted">{b}</div>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>
      </Section>
    </>
  );
}

export default async function ProductSlugPage({ params }: Props) {
  const { slug } = await params;

  const product = products.find((p) => p.slug === slug);

  if (!product) return notFound();

  const isFlagship = product.slug === "sovereign-vault-ai-platform";

  return (
    <Container>
      {isFlagship ? (
        <FlagshipStory />
      ) : (
        <>
          <div className="glass borderGlow rounded-2xl p-8">
            <div className="text-sm font-semibold text-gold">
              {site.taglineTop}. {site.taglineBottom}.
            </div>

            <h1 className="mt-3 text-3xl font-semibold tracking-tight">
              {product.name}
            </h1>

            <p className="mt-3 max-w-3xl text-sm text-muted">
              {product.oneLiner}
            </p>

            <div className="mt-5 flex flex-wrap items-center gap-2">
              <Badge>{product.priceTier}</Badge>
              <Badge>{site.pricingNote}</Badge>
            </div>
          </div>

          <Section title="Outcomes">
            <ul className="list-disc space-y-1 pl-5 text-sm text-muted">
              {product.outcomes.map((x) => (
                <li key={x}>{x}</li>
              ))}
            </ul>
          </Section>

          <Section title="Includes">
            <ul className="list-disc space-y-1 pl-5 text-sm text-muted">
              {product.includes.map((x) => (
                <li key={x}>{x}</li>
              ))}
            </ul>
          </Section>
        </>
      )}

      <CTA />
      <div className="py-10" />
    </Container>
  );
}
