import { notFound } from "next/navigation";
import { Container } from "@/components/Container";
import { Section } from "@/components/Section";
import { CTA } from "@/components/CTA";
import { Badge } from "@/components/Badge";
import { products } from "@/content/products";
import { site } from "@/content/site";

export function generateStaticParams() {
  return products.map((p) => ({ slug: p.slug }));
}

function ScreenshotFrame({
  title,
  caption,
}: {
  title: string;
  caption: string;
}) {
  return (
    <div className="rounded-2xl border border-line glass shadow-soft overflow-hidden">
      <div className="flex items-center justify-between border-b border-line bg-bg px-4 py-3">
        <div className="flex items-center gap-2">
          <div className="h-2.5 w-2.5 rounded-full bg-line" />
          <div className="h-2.5 w-2.5 rounded-full bg-line" />
          <div className="h-2.5 w-2.5 rounded-full bg-line" />
        </div>
        <div className="text-xs text-muted">{title}</div>
      </div>

      <div className="p-4">
        <div className="h-7 w-2/3 rounded-lg bg-bg" />
        <div className="mt-3 grid gap-2">
          <div className="h-3 w-full rounded bg-bg" />
          <div className="h-3 w-11/12 rounded bg-bg" />
          <div className="h-3 w-10/12 rounded bg-bg" />
        </div>

        <div className="mt-4 grid grid-cols-3 gap-2">
          <div className="h-12 rounded-xl bg-bg" />
          <div className="h-12 rounded-xl bg-bg" />
          <div className="h-12 rounded-xl bg-bg" />
        </div>

        <div className="mt-4 text-xs text-muted">{caption}</div>
      </div>
    </div>
  );
}

function FlagshipStory() {
  return (
    <>
      <div className="glass borderGlow rounded-2xl p-8">
        <div className="text-sm font-semibold text-gold">
          {site.taglineTop}. {site.taglineBottom}.
        </div>

        <h1 className="mt-3 text-3xl font-semibold tracking-tight">
          Sovereign Vault AI Platform
        </h1>

        <p className="mt-3 max-w-3xl text-sm text-muted">
          A flagship transaction platform for high value reservations, deposits, approvals, fraud resistance, and evidence grade audit trails.
          Built for premium brands that need speed, proof, and control.
        </p>

        <div className="mt-5 flex flex-wrap items-center gap-2">
          <Badge>Flagship</Badge>
          <Badge>Projects from 100,000 AED+</Badge>
          <Badge>Luxury Automotive Primary</Badge>
        </div>

        <div className="mt-6 grid gap-3 md:grid-cols-3">
          <div className="rounded-2xl border border-line bg-bg p-5">
            <div className="text-sm font-semibold">Less work</div>
            <div className="mt-2 text-sm text-muted">
              AI triage, automated routing, guided workflows, and evidence packs generated by the system.
            </div>
          </div>
          <div className="rounded-2xl border border-line bg-bg p-5">
            <div className="text-sm font-semibold">More flow</div>
            <div className="mt-2 text-sm text-muted">
              Reservations, deposits, and approvals move forward with tight controls and minimal friction.
            </div>
          </div>
          <div className="rounded-2xl border border-line bg-bg p-5">
            <div className="text-sm font-semibold">More proof</div>
            <div className="mt-2 text-sm text-muted">
              Every action is time stamped. Every decision has a trail. Every dispute has an evidence pack.
            </div>
          </div>
        </div>
      </div>

      <Section
        title="A luxury sales story that converts"
        subtitle="Your customer sees clarity and confidence. Your team sees control and traceability."
      >
        <div className="grid gap-4 md:grid-cols-2">
          <div className="glass borderGlow rounded-2xl p-6">
            <div className="text-sm font-semibold">Customer experience</div>
            <ul className="mt-3 list-disc space-y-1 pl-5 text-sm text-muted">
              <li>Reserve a specific asset with clear hold rules</li>
              <li>Pay a deposit with transparent disclosures and confirmations</li>
              <li>Track status in a secure portal</li>
              <li>Request more media, inspections, or appointments without chaos</li>
              <li>Receive receipts and acceptance proof automatically</li>
            </ul>
          </div>

          <div className="glass borderGlow rounded-2xl p-6">
            <div className="text-sm font-semibold">Internal operations</div>
            <ul className="mt-3 list-disc space-y-1 pl-5 text-sm text-muted">
              <li>Approvals, overrides, and exceptions are controlled</li>
              <li>Fraud signals route into a review queue with AI assisted triage</li>
              <li>Every staff action is logged and time stamped</li>
              <li>Evidence packs export in seconds</li>
              <li>Automation reduces repetitive admin work</li>
            </ul>
          </div>
        </div>
      </Section>

      <Section
        title="Screenshots style layout"
        subtitle="A visual sense of the platform modules. These are layout previews, not final UI."
      >
        <div className="glass borderGlow rounded-2xl overflow-hidden mb-6">
          <div className="relative">
            <img
              src="/mockups/vault-dashboard-mockup.jpg"
              alt="Sovereign Vault AI Platform mockup"
              className="w-full object-cover"
            />
            <div className="absolute inset-0 bg-gradient-to-t from-bg/70 via-transparent to-transparent" />
          </div>
          <div className="p-5 text-xs text-muted">Luxury mockup preview for the flagship platform dashboard. Final UI is bespoke per client.</div>
        </div>
<div className="grid gap-4 md:grid-cols-2 mb-6">
  <div className="glass borderGlow rounded-2xl overflow-hidden">
    <div className="relative">
      <img
        src="/mockups/case-queue-mockup.jpg"
        alt="Flagship case queue mockup"
        className="w-full object-cover"
      />
      <div className="absolute inset-0 bg-gradient-to-t from-bg/70 via-transparent to-transparent" />
    </div>
    <div className="p-5 text-xs text-muted">Case queue mockup for flagged events and approvals.</div>
  </div>

  <div className="glass borderGlow rounded-2xl overflow-hidden">
    <div className="relative">
      <img
        src="/mockups/metrics-mockup.jpg"
        alt="Flagship metrics mockup"
        className="w-full object-cover"
      />
      <div className="absolute inset-0 bg-gradient-to-t from-bg/70 via-transparent to-transparent" />
    </div>
    <div className="p-5 text-xs text-muted">Monitoring and performance metrics mockup for controls.</div>
  </div>
</div>
        <div className="grid gap-4 md:grid-cols-2">
          <ScreenshotFrame
            title="Reservation and Deposit Flow"
            caption="Hold rules, deposit logic, disclosures, receipts, and status timeline."
          />
          <ScreenshotFrame
            title="Admin Approvals Console"
            caption="Approvals, overrides, thresholds, and exception handling with full traceability."
          />
          <ScreenshotFrame
            title="Fraud Controls and Monitoring"
            caption="Risk scoring, velocity rules, identity resolution, monitoring, and alerts."
          />
          <ScreenshotFrame
            title="Evidence Vault Export"
            caption="Transaction history, acceptances, communications, and receipts packaged for disputes."
          />
          <ScreenshotFrame
            title="Case Management Queue"
            caption="Review, decision, notes, and evidence for flagged events."
          />
          <ScreenshotFrame
            title="Automation and Integrations"
            caption="Webhooks, notifications, routing, and system to system integration points."
          />
        </div>
      </Section>

      <Section
        title="Core modules"
        subtitle="The platform is built from modules. You can deploy all at once or phase it."
      >
        <div className="grid gap-4 md:grid-cols-2">
          <div className="glass borderGlow rounded-2xl p-6">
            <div className="text-sm font-semibold">Transaction layer</div>
            <ul className="mt-3 list-disc space-y-1 pl-5 text-sm text-muted">
              <li>Reservation workflow (hold, confirm, expire, release)</li>
              <li>Deposit logic (refundable vs non refundable, timing windows, disclosures)</li>
              <li>Customer portal (status, receipts, documents, next steps)</li>
              <li>Admin tools (approvals, overrides, exception notes)</li>
            </ul>
          </div>

          <div className="glass borderGlow rounded-2xl p-6">
            <div className="text-sm font-semibold">Controls and proof</div>
            <ul className="mt-3 list-disc space-y-1 pl-5 text-sm text-muted">
              <li>Audit trail and version history</li>
              <li>Evidence pack export for disputes</li>
              <li>Fraud controls layer (risk scoring, velocity, identity resolution)</li>
              <li>Optional AML workflow suite (KYC style onboarding, monitoring, case handling)</li>
            </ul>
          </div>
        </div>
      </Section>
    </>
  );
}

export default function ProductSlugPage({
  params,
}: {
  params: { slug: string };
}) {
  const product = products.find((p) => p.slug === params.slug);

  if (!product) return notFound();

  const isFlagship = product.slug === "sovereign-vault-ai-platform";

  return (
    <Container>
      {isFlagship ? (
        <FlagshipStory />
      ) : (
        <>
          <div className="glass borderGlow rounded-2xl p-8">
            <div className="text-sm font-semibold text-gold">
              {site.taglineTop}. {site.taglineBottom}.
            </div>

            <h1 className="mt-3 text-3xl font-semibold tracking-tight">
              {product.name}
            </h1>

            <p className="mt-3 max-w-3xl text-sm text-muted">{product.oneLiner}</p>

            <div className="mt-5 flex flex-wrap items-center gap-2">
              <Badge>{product.priceTier}</Badge>
              <Badge>{site.pricingNote}</Badge>
            </div>
          </div>

          <Section title="Outcomes">
            <ul className="list-disc space-y-1 pl-5 text-sm text-muted">
              {product.outcomes.map((x) => (
                <li key={x}>{x}</li>
              ))}
            </ul>
          </Section>

          <Section title="Includes">
            <ul className="list-disc space-y-1 pl-5 text-sm text-muted">
              {product.includes.map((x) => (
                <li key={x}>{x}</li>
              ))}
            </ul>
          </Section>
        </>
      )}

      <CTA />
      <div className="py-10" />
    </Container>
  );
}
